/*
* This file was generated by PolyTaint Truffle instrument - ERO project 2022
*
* The MIT License (MIT)
* Copyright (c) 2022 Peterson Yuhala
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this software
* and associated documentation files (the "Software"), to deal in the Software without restriction,
* including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
* subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all copies or substantial
* portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
* TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
* THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


package polytaint;
import org.graalvm.nativeimage.CurrentIsolate;
import org.graalvm.nativeimage.IsolateThread;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.c.function.CFunction;
import org.graalvm.polyglot.*;
import org.graalvm.polyglot.proxy.*;
import org.graalvm.polyglot.*;

public class Trusted {

    public static void main(String[] args) {
        System.out.println("Trusted dummy main!!");
    }
    public static void poly_2(){
        Context context = Context.newBuilder().allowAllAccess(true).build();
        Value funcD = context.asValue(Trusted.class).getMember("static").getMember("funcD");
        Value funcA = context.asValue(Trusted.class).getMember("static").getMember("funcA");
        Value funcN = context.asValue(Trusted.class).getMember("static").getMember("funcN");
        Value sayHello = context.asValue(Trusted.class).getMember("static").getMember("sayHello");
        context.eval("js","function poly_2_wrapper(funcD,funcA,funcN,sayHello){function poly_2() {    var poly2_secInt = Polyglot.eval(\"secL\", \"sInt(222)\");    console.log('poly2_secInt: ' + poly2_secInt);}poly_2();}poly_2_wrapper;").execute(funcD,funcA,funcN,sayHello);
    }

    public static double funcA(){
        Context context = Context.newBuilder().allowAllAccess(true).build();
        Value poly_2 = context.asValue(Trusted.class).getMember("static").getMember("poly_2");
        Value funcD = context.asValue(Trusted.class).getMember("static").getMember("funcD");
        Value funcN = context.asValue(Trusted.class).getMember("static").getMember("funcN");
        Value sayHello = context.asValue(Trusted.class).getMember("static").getMember("sayHello");
        return context.eval("js","function funcA_wrapper(poly_2,funcD,funcN,sayHello){function funcA() {    var sec_int_a = Polyglot.eval(\"secL\", \"sDouble(125.45)\");    var resC = 123 + 456 * 789 / 111 - sec_int_a;    var resN = funcN(sec_int_a, 2);    var retd = funcD(resC);    var a = 4;    for (let i = 0; i < 5; i++) {        a = a + i;        for (let j = 0; j < 2; j++) {            resN = resC + a;        }    }    sayHello();    console.log('resN in funcA is : ' + resN);    return resC;}return funcA();}funcA_wrapper;").execute(poly_2,funcD,funcN,sayHello).asDouble();
    }

    public static double funcD(double param1){
        Context context = Context.newBuilder().allowAllAccess(true).build();
        Value poly_2 = context.asValue(Trusted.class).getMember("static").getMember("poly_2");
        Value funcA = context.asValue(Trusted.class).getMember("static").getMember("funcA");
        Value funcN = context.asValue(Trusted.class).getMember("static").getMember("funcN");
        Value sayHello = context.asValue(Trusted.class).getMember("static").getMember("sayHello");
        return context.eval("js","function funcD_wrapper(poly_2,funcA,funcN,sayHello,param1){function funcD(paramD) {    var res = funcN(paramD, 2);    console.log('funcD res from N: ' + res);    return res;}return funcD(param1);}funcD_wrapper;").execute(poly_2,funcA,funcN,sayHello,param1).asDouble();
    }

    public static double funcN(double param1, int param2){
        Context context = Context.newBuilder().allowAllAccess(true).build();
        Value poly_2 = context.asValue(Trusted.class).getMember("static").getMember("poly_2");
        Value funcD = context.asValue(Trusted.class).getMember("static").getMember("funcD");
        Value funcA = context.asValue(Trusted.class).getMember("static").getMember("funcA");
        Value sayHello = context.asValue(Trusted.class).getMember("static").getMember("sayHello");
        return context.eval("js","function funcN_wrapper(poly_2,funcD,funcA,sayHello,param1,param2){function funcN(param, n) {    console.log('funcN: ' + param);    return param * n;}return funcN(param1, param2);}funcN_wrapper;").execute(poly_2,funcD,funcA,sayHello,param1,param2).asDouble();
    }

    public static void sayHello(){
        sayHello_proxy();
    }

    @CEntryPoint(name = "poly_2_entry")
    public static void poly_2_entry(IsolateThread thread){
        poly_2();
    }

    @CEntryPoint(name = "funcA_entry")
    public static double funcA_entry(IsolateThread thread){
        return funcA();
    }

    @CFunction
    public static native void sayHello_proxy();
}
