/*
* This file was generated by PolyTaint Truffle instrument - ERO project 2022
*
* The MIT License (MIT)
* Copyright (c) 2022 Peterson Yuhala
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this software
* and associated documentation files (the "Software"), to deal in the Software without restriction,
* including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
* subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all copies or substantial
* portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
* TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
* THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


package polytaint;
import org.graalvm.nativeimage.CurrentIsolate;
import org.graalvm.nativeimage.IsolateThread;
import org.graalvm.nativeimage.c.function.CEntryPoint;
import org.graalvm.nativeimage.c.function.CFunction;
import org.graalvm.polyglot.*;
import org.graalvm.polyglot.proxy.*;
import org.graalvm.polyglot.*;

public class Untrusted {

    public static void main(String[] args) {
        System.out.println("Main: untrusted partition!!");
        Context context = Context.newBuilder().allowAllAccess(true).build();
        Value poly_2 = context.asValue(Untrusted.class).getMember("static").getMember("poly_2");
        Value funcD = context.asValue(Untrusted.class).getMember("static").getMember("funcD");
        Value funcA = context.asValue(Untrusted.class).getMember("static").getMember("funcA");
        Value funcN = context.asValue(Untrusted.class).getMember("static").getMember("funcN");
        Value sayHello = context.asValue(Untrusted.class).getMember("static").getMember("sayHello");
        context.eval("js","function main_wrapper(poly_2,funcD,funcA,funcN,sayHello){sayHello();var retd = funcD(5.0);var reta = funcA();var poly = poly_2();console.log(\">>>>>>>> at the end of javascript file >>>>>>\")}main_wrapper;").execute(poly_2,funcD,funcA,funcN,sayHello);
    }
    public static void poly_2(){
        poly_2_proxy();
    }

    public static double funcA(){
        return funcA_proxy();
    }

    public static double funcD(double param1){
        Context context = Context.newBuilder().allowAllAccess(true).build();
        Value poly_2 = context.asValue(Untrusted.class).getMember("static").getMember("poly_2");
        Value funcA = context.asValue(Untrusted.class).getMember("static").getMember("funcA");
        Value funcN = context.asValue(Untrusted.class).getMember("static").getMember("funcN");
        Value sayHello = context.asValue(Untrusted.class).getMember("static").getMember("sayHello");
        return context.eval("js","function funcD_wrapper(poly_2,funcA,funcN,sayHello,param1){function funcD(paramD) {    var res = funcN(paramD, 2);    console.log('funcD res from N: ' + res);    return res;}return funcD(param1);}funcD_wrapper;").execute(poly_2,funcA,funcN,sayHello,param1).asDouble();
    }

    public static double funcN(double param1, int param2){
        Context context = Context.newBuilder().allowAllAccess(true).build();
        Value poly_2 = context.asValue(Untrusted.class).getMember("static").getMember("poly_2");
        Value funcD = context.asValue(Untrusted.class).getMember("static").getMember("funcD");
        Value funcA = context.asValue(Untrusted.class).getMember("static").getMember("funcA");
        Value sayHello = context.asValue(Untrusted.class).getMember("static").getMember("sayHello");
        return context.eval("js","function funcN_wrapper(poly_2,funcD,funcA,sayHello,param1,param2){function funcN(param, n) {    console.log('funcN: ' + param);    return param * n;}return funcN(param1, param2);}funcN_wrapper;").execute(poly_2,funcD,funcA,sayHello,param1,param2).asDouble();
    }

    public static void sayHello(){
        Context context = Context.newBuilder().allowAllAccess(true).build();
        Value poly_2 = context.asValue(Untrusted.class).getMember("static").getMember("poly_2");
        Value funcD = context.asValue(Untrusted.class).getMember("static").getMember("funcD");
        Value funcA = context.asValue(Untrusted.class).getMember("static").getMember("funcA");
        Value funcN = context.asValue(Untrusted.class).getMember("static").getMember("funcN");
        context.eval("js","function sayHello_wrapper(poly_2,funcD,funcA,funcN){function sayHello() {    console.log('++++++++++++ Hello from javascript file +++++++++++');}sayHello();}sayHello_wrapper;").execute(poly_2,funcD,funcA,funcN);
    }

    @CEntryPoint(name = "sayHello_entry")
    public static void sayHello_entry(IsolateThread thread){
        sayHello();
    }

    @CFunction
    public static native void poly_2_proxy();
    @CFunction
    public static native double funcA_proxy();
}
